"""
Module with all the telegram handlers.
Other user-facing handlers are autogenerated in `bot.py`
"""

from .access_config_handler import (
    add_manager,
    change_board,
    get_config,
    get_config_jobs,
    reload_config_jobs,
    set_config,
)

# Debug handlers (also developer, but only needed for debug)
from .clean_chat_data_handler import clean_chat_data
from .enroll_curator_handler import enroll_curator

# Error handler
from .error_handler import error
from .get_chat_data_handler import get_chat_data
from .get_chat_id_handler import get_chat_id_handler as get_chat_id
from .get_managers_handler import get_managers
from .get_members_for_role_handler import get_members_for_role

# Admin (developer) handlers
from .get_roles_for_member_handler import get_roles_for_member
from .get_tasks_report_handler import get_tasks_report, get_tasks_report_advanced
from .help_handler import help
from .list_chats_handler import list_chats
from .list_job_handler import list_jobs
from .manage_reminders_handler import manage_all_reminders, manage_reminders
from .mute_errors_handler import mute_errors, unmute_errors
from .set_log_level_handler import set_log_level

# User-facing handlers
from .start_handler import start

# Plain text message handler
from .user_message_handler import (
    handle_callback_query,
    handle_new_members,
    handle_user_message,
)
