"""
Module with all the telegram handlers.
Other user-facing handlers are autogenerated in `bot.py`
"""

# User-facing handlers
from .start_handler import start
from .help_handler import help
from .get_tasks_report_handler import get_tasks_report
from .get_chat_id_handler import get_chat_id_handler as get_chat_id

# Plain text message handler
from .user_message_handler import handle_callback_query, handle_user_message, handle_new_members
# Error handler
from .error_handler import error

# Admin (developer) handlers
from .list_job_handler import list_jobs
from .set_log_level_handler import set_log_level
from .mute_errors_handler import mute_errors, unmute_errors
from .access_config_handler import get_config, set_config, add_manager, change_board
